# Generated by Django 4.1 on 2022-10-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=2, null=0)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=2)),
                ('number', models.PositiveIntegerField()),
                ('agency', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('C', 'Checking Account'), ('S', 'Saving Account'), ('W', 'Wage Account')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=55)),
                ('state', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('disctrict', models.CharField(max_length=55)),
                ('street', models.CharField(max_length=55)),
                ('number', models.PositiveSmallIntegerField()),
                ('complement', models.CharField(max_length=55)),
                ('zip_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('is_active', models.BooleanField()),
                ('birth_date', models.DateField()),
                ('cnpj', models.CharField(max_length=18)),
                ('is_employed', models.BooleanField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undefined')], default='U', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=2)),
                ('value_fees', models.DecimalField(decimal_places=2, max_digits=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=2)),
                ('expiration', models.DateField()),
                ('condition', models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Paying'), ('W', 'Waiting')], default='W', max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Loan', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.client')),
            ],
        ),
    ]
