# Generated by Django 4.1 on 2022-10-31 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=2, null=0)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=2)),
                ('number', models.PositiveIntegerField()),
                ('agency', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('C', 'Checking Account'), ('S', 'Saving Account'), ('W', 'Wage Account')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('is_active', models.BooleanField()),
                ('birth_date', models.DateField()),
                ('cnpj', models.CharField(max_length=18)),
                ('is_employed', models.BooleanField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undefined')], default='U', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=2)),
                ('value_fees', models.DecimalField(decimal_places=2, max_digits=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=2)),
                ('expiration', models.DateField()),
                ('condition', models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Paying'), ('W', 'Waiting')], default='W', max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Loan', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient', to='accounts.client')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installments', models.PositiveSmallIntegerField(null=1)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('cvv', models.PositiveSmallIntegerField(max_length=3)),
                ('expiration_date', models.DateField()),
                ('state', models.CharField(choices=[('B', 'Blocked'), ('A', 'Active')], max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('E', 'Entries'), ('W', 'Withdrawals')], max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=55)),
                ('state', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('disctrict', models.CharField(max_length=55)),
                ('street', models.CharField(max_length=55)),
                ('number', models.PositiveSmallIntegerField()),
                ('complement', models.CharField(max_length=55)),
                ('zip_code', models.CharField(max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.client')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.client'),
        ),
    ]
